#!/bin/bash
sudo apt install apache2 -y
# Update package manager
sudo yum update -y

# Install dependencies
sudo yum install -y ruby wget

# Download and install CodeDeploy agent
wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
chmod +x ./install
sudo ./install auto

# Start CodeDeploy agent
sudo service codedeploy-agent start

# Check CodeDeploy agent status
sudo service codedeploy-agent status
